version: '3.1'
networks:
  app-tier:
    driver: bridge
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27027:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    networks:
      - app-tier
    volumes:
      - "mongo-volume:/data/db"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 28081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    networks:
      - app-tier

  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - 28080:80
    networks:
      - app-tier
    depends_on:
      - mongo

volumes:
  mongo-volume:
